pull_request_rules:
  - name: automatic merge on CI and Netlify success
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=netlify/yeejian/deploy-preview
    actions:
      merge:
        method: merge
