language: node_js
node_js:
  - '13'
install:
  - yarn add codecov
script:
  - yarn install
  - yarn run lint
  - yarn run test:coverage --runInBand --no-cache
  - yarn run test --runInBand --no-cache
  - codecov
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: gatsby

cache:
  directories:
    - node_modules

