language: node_js
node_js:
  - '10'
install:
  - npm install -g codecov
  - npm install webpack
script:
  - npm install
  - npm run lint
  - npm run test:coverage --runInBand --no-cache
  - npm run test --runInBand --no-cache
  - codecov
  - NODE_OPTIONS=--max_old_space_size=4096 npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: gatsby

cache:
  directories:
    - node_modules

